server:
  port: 10086
spring:
  application:
    name: my-gateway
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
          - Path=/user/**
          
        #- id: zpark-route
         # uri: http//www.zpark.com.cn/
         # predicates:
         # - Path=/zpark          
          
eureka:
   client:
    service-url: 
      defaultZone: 
         http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
   instance:
    prefer-ip-address: true